// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.0
// source: client/v1/client.proto

package clientrpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_client_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_client_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountType   string                 `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_client_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_client_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *Network) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdvertisedRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Cidr          string                 `protobuf:"bytes,4,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Approved      bool                   `protobuf:"varint,5,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertisedRoute) Reset() {
	*x = AdvertisedRoute{}
	mi := &file_client_v1_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertisedRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertisedRoute) ProtoMessage() {}

func (x *AdvertisedRoute) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertisedRoute.ProtoReflect.Descriptor instead.
func (*AdvertisedRoute) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{4}
}

func (x *AdvertisedRoute) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *AdvertisedRoute) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AdvertisedRoute) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AdvertisedRoute) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *AdvertisedRoute) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type Plan struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlanId          string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MonthlyPrice    *uint64                `protobuf:"varint,3,opt,name=monthly_price,json=monthlyPrice,proto3,oneof" json:"monthly_price,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	BillingProvider string                 `protobuf:"bytes,5,opt,name=billing_provider,json=billingProvider,proto3" json:"billing_provider,omitempty"`
	NetworkLimit    uint64                 `protobuf:"varint,6,opt,name=network_limit,json=networkLimit,proto3" json:"network_limit,omitempty"`
	NodeLimit       uint64                 `protobuf:"varint,7,opt,name=node_limit,json=nodeLimit,proto3" json:"node_limit,omitempty"`
	UserLimit       uint64                 `protobuf:"varint,8,opt,name=user_limit,json=userLimit,proto3" json:"user_limit,omitempty"`
	Public          bool                   `protobuf:"varint,9,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_client_v1_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{5}
}

func (x *Plan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetMonthlyPrice() uint64 {
	if x != nil && x.MonthlyPrice != nil {
		return *x.MonthlyPrice
	}
	return 0
}

func (x *Plan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Plan) GetBillingProvider() string {
	if x != nil {
		return x.BillingProvider
	}
	return ""
}

func (x *Plan) GetNetworkLimit() uint64 {
	if x != nil {
		return x.NetworkLimit
	}
	return 0
}

func (x *Plan) GetNodeLimit() uint64 {
	if x != nil {
		return x.NodeLimit
	}
	return 0
}

func (x *Plan) GetUserLimit() uint64 {
	if x != nil {
		return x.UserLimit
	}
	return 0
}

func (x *Plan) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_client_v1_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{6}
}

func (x *Subscription) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Networks      uint64                 `protobuf:"varint,2,opt,name=networks,proto3" json:"networks,omitempty"`
	Nodes         uint64                 `protobuf:"varint,3,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Users         uint64                 `protobuf:"varint,4,opt,name=users,proto3" json:"users,omitempty"`
	NetworkLimit  uint64                 `protobuf:"varint,5,opt,name=network_limit,json=networkLimit,proto3" json:"network_limit,omitempty"`
	NodeLimit     uint64                 `protobuf:"varint,6,opt,name=node_limit,json=nodeLimit,proto3" json:"node_limit,omitempty"`
	UserLimit     uint64                 `protobuf:"varint,7,opt,name=user_limit,json=userLimit,proto3" json:"user_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_client_v1_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Usage) GetNetworks() uint64 {
	if x != nil {
		return x.Networks
	}
	return 0
}

func (x *Usage) GetNodes() uint64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *Usage) GetUsers() uint64 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *Usage) GetNetworkLimit() uint64 {
	if x != nil {
		return x.NetworkLimit
	}
	return 0
}

func (x *Usage) GetNodeLimit() uint64 {
	if x != nil {
		return x.NodeLimit
	}
	return 0
}

func (x *Usage) GetUserLimit() uint64 {
	if x != nil {
		return x.UserLimit
	}
	return 0
}

type Checkout struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckoutId      string                 `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ConfirmationUrl string                 `protobuf:"bytes,5,opt,name=confirmation_url,json=confirmationUrl,proto3" json:"confirmation_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Checkout) Reset() {
	*x = Checkout{}
	mi := &file_client_v1_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout) ProtoMessage() {}

func (x *Checkout) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout.ProtoReflect.Descriptor instead.
func (*Checkout) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{8}
}

func (x *Checkout) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *Checkout) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Checkout) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Checkout) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Checkout) GetConfirmationUrl() string {
	if x != nil {
		return x.ConfirmationUrl
	}
	return ""
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Number        string                 `protobuf:"bytes,5,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_client_v1_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{9}
}

func (x *Invoice) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Invoice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Invoice) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_client_v1_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{10}
}

func (x *ListAccountsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_client_v1_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListAccountsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksRequest) Reset() {
	*x = ListNetworksRequest{}
	mi := &file_client_v1_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksRequest) ProtoMessage() {}

func (x *ListNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksRequest.ProtoReflect.Descriptor instead.
func (*ListNetworksRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{12}
}

func (x *ListNetworksRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListNetworksRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*Network             `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksResponse) Reset() {
	*x = ListNetworksResponse{}
	mi := &file_client_v1_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksResponse) ProtoMessage() {}

func (x *ListNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksResponse.ProtoReflect.Descriptor instead.
func (*ListNetworksResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{13}
}

func (x *ListNetworksResponse) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ListNetworksResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAdvertisedRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdvertisedRoutesRequest) Reset() {
	*x = ListAdvertisedRoutesRequest{}
	mi := &file_client_v1_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdvertisedRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvertisedRoutesRequest) ProtoMessage() {}

func (x *ListAdvertisedRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvertisedRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListAdvertisedRoutesRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{14}
}

func (x *ListAdvertisedRoutesRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ListAdvertisedRoutesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAdvertisedRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*AdvertisedRoute     `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdvertisedRoutesResponse) Reset() {
	*x = ListAdvertisedRoutesResponse{}
	mi := &file_client_v1_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdvertisedRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvertisedRoutesResponse) ProtoMessage() {}

func (x *ListAdvertisedRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvertisedRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListAdvertisedRoutesResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{15}
}

func (x *ListAdvertisedRoutesResponse) GetRoutes() []*AdvertisedRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ListAdvertisedRoutesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListBillingPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBillingPlansRequest) Reset() {
	*x = ListBillingPlansRequest{}
	mi := &file_client_v1_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillingPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillingPlansRequest) ProtoMessage() {}

func (x *ListBillingPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillingPlansRequest.ProtoReflect.Descriptor instead.
func (*ListBillingPlansRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{16}
}

type ListBillingPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBillingPlansResponse) Reset() {
	*x = ListBillingPlansResponse{}
	mi := &file_client_v1_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillingPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillingPlansResponse) ProtoMessage() {}

func (x *ListBillingPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillingPlansResponse.ProtoReflect.Descriptor instead.
func (*ListBillingPlansResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{17}
}

func (x *ListBillingPlansResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type GetBillingSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingSubscriptionRequest) Reset() {
	*x = GetBillingSubscriptionRequest{}
	mi := &file_client_v1_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingSubscriptionRequest) ProtoMessage() {}

func (x *GetBillingSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetBillingSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{18}
}

func (x *GetBillingSubscriptionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBillingSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingSubscriptionResponse) Reset() {
	*x = GetBillingSubscriptionResponse{}
	mi := &file_client_v1_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingSubscriptionResponse) ProtoMessage() {}

func (x *GetBillingSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetBillingSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{19}
}

func (x *GetBillingSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type GetBillingUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingUsageRequest) Reset() {
	*x = GetBillingUsageRequest{}
	mi := &file_client_v1_client_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingUsageRequest) ProtoMessage() {}

func (x *GetBillingUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingUsageRequest.ProtoReflect.Descriptor instead.
func (*GetBillingUsageRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{20}
}

func (x *GetBillingUsageRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBillingUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         *Usage                 `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingUsageResponse) Reset() {
	*x = GetBillingUsageResponse{}
	mi := &file_client_v1_client_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingUsageResponse) ProtoMessage() {}

func (x *GetBillingUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingUsageResponse.ProtoReflect.Descriptor instead.
func (*GetBillingUsageResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{21}
}

func (x *GetBillingUsageResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// Checkout retries must reuse this key. The service must check billing rights
// and persist the idempotent result before returning a provider URL.
type OperationMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationMetadata) Reset() {
	*x = OperationMetadata{}
	mi := &file_client_v1_client_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationMetadata) ProtoMessage() {}

func (x *OperationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationMetadata.ProtoReflect.Descriptor instead.
func (*OperationMetadata) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{22}
}

func (x *OperationMetadata) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateBillingCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	BillingPeriod string                 `protobuf:"bytes,3,opt,name=billing_period,json=billingPeriod,proto3" json:"billing_period,omitempty"`
	Operation     *OperationMetadata     `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingCheckoutRequest) Reset() {
	*x = CreateBillingCheckoutRequest{}
	mi := &file_client_v1_client_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingCheckoutRequest) ProtoMessage() {}

func (x *CreateBillingCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingCheckoutRequest.ProtoReflect.Descriptor instead.
func (*CreateBillingCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{23}
}

func (x *CreateBillingCheckoutRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateBillingCheckoutRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateBillingCheckoutRequest) GetBillingPeriod() string {
	if x != nil {
		return x.BillingPeriod
	}
	return ""
}

func (x *CreateBillingCheckoutRequest) GetOperation() *OperationMetadata {
	if x != nil {
		return x.Operation
	}
	return nil
}

type CreateBillingCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkout      *Checkout              `protobuf:"bytes,1,opt,name=checkout,proto3" json:"checkout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingCheckoutResponse) Reset() {
	*x = CreateBillingCheckoutResponse{}
	mi := &file_client_v1_client_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingCheckoutResponse) ProtoMessage() {}

func (x *CreateBillingCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingCheckoutResponse.ProtoReflect.Descriptor instead.
func (*CreateBillingCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{24}
}

func (x *CreateBillingCheckoutResponse) GetCheckout() *Checkout {
	if x != nil {
		return x.Checkout
	}
	return nil
}

type ListBillingInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBillingInvoicesRequest) Reset() {
	*x = ListBillingInvoicesRequest{}
	mi := &file_client_v1_client_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillingInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillingInvoicesRequest) ProtoMessage() {}

func (x *ListBillingInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillingInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListBillingInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{25}
}

func (x *ListBillingInvoicesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListBillingInvoicesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListBillingInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBillingInvoicesResponse) Reset() {
	*x = ListBillingInvoicesResponse{}
	mi := &file_client_v1_client_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillingInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillingInvoicesResponse) ProtoMessage() {}

func (x *ListBillingInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillingInvoicesResponse.ProtoReflect.Descriptor instead.
func (*ListBillingInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{26}
}

func (x *ListBillingInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *ListBillingInvoicesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// Discovery is accepted only for a currently authorized connector and policy
// hash. Addresses and the bounded lease must be validated by the service.
type ReportApplicationDiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	PolicyHash    string                 `protobuf:"bytes,3,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportApplicationDiscoveryRequest) Reset() {
	*x = ReportApplicationDiscoveryRequest{}
	mi := &file_client_v1_client_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportApplicationDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportApplicationDiscoveryRequest) ProtoMessage() {}

func (x *ReportApplicationDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportApplicationDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*ReportApplicationDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{27}
}

func (x *ReportApplicationDiscoveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportApplicationDiscoveryRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ReportApplicationDiscoveryRequest) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

func (x *ReportApplicationDiscoveryRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ReportApplicationDiscoveryRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ReportApplicationDiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportApplicationDiscoveryResponse) Reset() {
	*x = ReportApplicationDiscoveryResponse{}
	mi := &file_client_v1_client_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportApplicationDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportApplicationDiscoveryResponse) ProtoMessage() {}

func (x *ReportApplicationDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportApplicationDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*ReportApplicationDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{28}
}

type GetFlowLogPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowLogPolicyRequest) Reset() {
	*x = GetFlowLogPolicyRequest{}
	mi := &file_client_v1_client_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowLogPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowLogPolicyRequest) ProtoMessage() {}

func (x *GetFlowLogPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowLogPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetFlowLogPolicyRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{29}
}

func (x *GetFlowLogPolicyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// A policy grants collection only during this interval and consent generation.
type GetFlowLogPolicyResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConsentVersion      uint64                 `protobuf:"varint,1,opt,name=consent_version,json=consentVersion,proto3" json:"consent_version,omitempty"`
	CollectionNotBefore *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=collection_not_before,json=collectionNotBefore,proto3" json:"collection_not_before,omitempty"`
	CollectionExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collection_expires_at,json=collectionExpiresAt,proto3" json:"collection_expires_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetFlowLogPolicyResponse) Reset() {
	*x = GetFlowLogPolicyResponse{}
	mi := &file_client_v1_client_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowLogPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowLogPolicyResponse) ProtoMessage() {}

func (x *GetFlowLogPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowLogPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetFlowLogPolicyResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{30}
}

func (x *GetFlowLogPolicyResponse) GetConsentVersion() uint64 {
	if x != nil {
		return x.ConsentVersion
	}
	return 0
}

func (x *GetFlowLogPolicyResponse) GetCollectionNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectionNotBefore
	}
	return nil
}

func (x *GetFlowLogPolicyResponse) GetCollectionExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectionExpiresAt
	}
	return nil
}

type ReportFlowLogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConsentVersion uint64                 `protobuf:"varint,2,opt,name=consent_version,json=consentVersion,proto3" json:"consent_version,omitempty"`
	Window         *FlowWindow            `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportFlowLogRequest) Reset() {
	*x = ReportFlowLogRequest{}
	mi := &file_client_v1_client_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFlowLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFlowLogRequest) ProtoMessage() {}

func (x *ReportFlowLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFlowLogRequest.ProtoReflect.Descriptor instead.
func (*ReportFlowLogRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{31}
}

func (x *ReportFlowLogRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportFlowLogRequest) GetConsentVersion() uint64 {
	if x != nil {
		return x.ConsentVersion
	}
	return 0
}

func (x *ReportFlowLogRequest) GetWindow() *FlowWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

// window_id is immutable across retries; acknowledgement requires durable
// acceptance under the still-valid collection consent.
type FlowWindow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WindowId        string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination     string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DestinationPort uint32                 `protobuf:"varint,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Decision        string                 `protobuf:"bytes,6,opt,name=decision,proto3" json:"decision,omitempty"`
	RuleId          string                 `protobuf:"bytes,7,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Bytes           uint64                 `protobuf:"varint,8,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Packets         uint64                 `protobuf:"varint,9,opt,name=packets,proto3" json:"packets,omitempty"`
	WindowStart     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FlowWindow) Reset() {
	*x = FlowWindow{}
	mi := &file_client_v1_client_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowWindow) ProtoMessage() {}

func (x *FlowWindow) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowWindow.ProtoReflect.Descriptor instead.
func (*FlowWindow) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{32}
}

func (x *FlowWindow) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *FlowWindow) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FlowWindow) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *FlowWindow) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *FlowWindow) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FlowWindow) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *FlowWindow) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *FlowWindow) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *FlowWindow) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *FlowWindow) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *FlowWindow) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

type ReportFlowLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFlowLogResponse) Reset() {
	*x = ReportFlowLogResponse{}
	mi := &file_client_v1_client_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFlowLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFlowLogResponse) ProtoMessage() {}

func (x *ReportFlowLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFlowLogResponse.ProtoReflect.Descriptor instead.
func (*ReportFlowLogResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{33}
}

func (x *ReportFlowLogResponse) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

var File_client_v1_client_proto protoreflect.FileDescriptor

const file_client_v1_client_proto_rawDesc = "" +
	"\n" +
	"\x16client/v1/client.proto\x12\x14endlessnet.client.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"6\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\"w\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\faccount_type\x18\x03 \x01(\tR\vaccountType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"<\n" +
	"\aNetwork\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x95\x01\n" +
	"\x0fAdvertisedRoute\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x12\n" +
	"\x04cidr\x18\x04 \x01(\tR\x04cidr\x12\x1a\n" +
	"\bapproved\x18\x05 \x01(\bR\bapproved\"\xb1\x02\n" +
	"\x04Plan\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\rmonthly_price\x18\x03 \x01(\x04H\x00R\fmonthlyPrice\x88\x01\x01\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12)\n" +
	"\x10billing_provider\x18\x05 \x01(\tR\x0fbillingProvider\x12#\n" +
	"\rnetwork_limit\x18\x06 \x01(\x04R\fnetworkLimit\x12\x1d\n" +
	"\n" +
	"node_limit\x18\a \x01(\x04R\tnodeLimit\x12\x1d\n" +
	"\n" +
	"user_limit\x18\b \x01(\x04R\tuserLimit\x12\x16\n" +
	"\x06public\x18\t \x01(\bR\x06publicB\x10\n" +
	"\x0e_monthly_price\"^\n" +
	"\fSubscription\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xd1\x01\n" +
	"\x05Usage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bnetworks\x18\x02 \x01(\x04R\bnetworks\x12\x14\n" +
	"\x05nodes\x18\x03 \x01(\x04R\x05nodes\x12\x14\n" +
	"\x05users\x18\x04 \x01(\x04R\x05users\x12#\n" +
	"\rnetwork_limit\x18\x05 \x01(\x04R\fnetworkLimit\x12\x1d\n" +
	"\n" +
	"node_limit\x18\x06 \x01(\x04R\tnodeLimit\x12\x1d\n" +
	"\n" +
	"user_limit\x18\a \x01(\x04R\tuserLimit\"\xa9\x01\n" +
	"\bCheckout\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12)\n" +
	"\x10confirmation_url\x18\x05 \x01(\tR\x0fconfirmationUrl\"\x8c\x01\n" +
	"\aInvoice\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06number\x18\x05 \x01(\tR\x06number\"L\n" +
	"\x13ListAccountsRequest\x125\n" +
	"\x04page\x18\x01 \x01(\v2!.endlessnet.client.v1.PageRequestR\x04page\"\x89\x01\n" +
	"\x14ListAccountsResponse\x129\n" +
	"\baccounts\x18\x01 \x03(\v2\x1d.endlessnet.client.v1.AccountR\baccounts\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".endlessnet.client.v1.PageResponseR\x04page\"k\n" +
	"\x13ListNetworksRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x125\n" +
	"\x04page\x18\x02 \x01(\v2!.endlessnet.client.v1.PageRequestR\x04page\"\x89\x01\n" +
	"\x14ListNetworksResponse\x129\n" +
	"\bnetworks\x18\x01 \x03(\v2\x1d.endlessnet.client.v1.NetworkR\bnetworks\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".endlessnet.client.v1.PageResponseR\x04page\"s\n" +
	"\x1bListAdvertisedRoutesRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x125\n" +
	"\x04page\x18\x02 \x01(\v2!.endlessnet.client.v1.PageRequestR\x04page\"\x95\x01\n" +
	"\x1cListAdvertisedRoutesResponse\x12=\n" +
	"\x06routes\x18\x01 \x03(\v2%.endlessnet.client.v1.AdvertisedRouteR\x06routes\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".endlessnet.client.v1.PageResponseR\x04page\"\x19\n" +
	"\x17ListBillingPlansRequest\"L\n" +
	"\x18ListBillingPlansResponse\x120\n" +
	"\x05plans\x18\x01 \x03(\v2\x1a.endlessnet.client.v1.PlanR\x05plans\">\n" +
	"\x1dGetBillingSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"h\n" +
	"\x1eGetBillingSubscriptionResponse\x12F\n" +
	"\fsubscription\x18\x01 \x01(\v2\".endlessnet.client.v1.SubscriptionR\fsubscription\"7\n" +
	"\x16GetBillingUsageRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"L\n" +
	"\x17GetBillingUsageResponse\x121\n" +
	"\x05usage\x18\x01 \x01(\v2\x1b.endlessnet.client.v1.UsageR\x05usage\"<\n" +
	"\x11OperationMetadata\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"\xc4\x01\n" +
	"\x1cCreateBillingCheckoutRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12%\n" +
	"\x0ebilling_period\x18\x03 \x01(\tR\rbillingPeriod\x12E\n" +
	"\toperation\x18\x04 \x01(\v2'.endlessnet.client.v1.OperationMetadataR\toperation\"[\n" +
	"\x1dCreateBillingCheckoutResponse\x12:\n" +
	"\bcheckout\x18\x01 \x01(\v2\x1e.endlessnet.client.v1.CheckoutR\bcheckout\"r\n" +
	"\x1aListBillingInvoicesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x125\n" +
	"\x04page\x18\x02 \x01(\v2!.endlessnet.client.v1.PageRequestR\x04page\"\x90\x01\n" +
	"\x1bListBillingInvoicesResponse\x129\n" +
	"\binvoices\x18\x01 \x03(\v2\x1d.endlessnet.client.v1.InvoiceR\binvoices\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".endlessnet.client.v1.PageResponseR\x04page\"\xc3\x01\n" +
	"!ReportApplicationDiscoveryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1f\n" +
	"\vpolicy_hash\x18\x03 \x01(\tR\n" +
	"policyHash\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\"$\n" +
	"\"ReportApplicationDiscoveryResponse\"2\n" +
	"\x17GetFlowLogPolicyRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xe3\x01\n" +
	"\x18GetFlowLogPolicyResponse\x12'\n" +
	"\x0fconsent_version\x18\x01 \x01(\x04R\x0econsentVersion\x12N\n" +
	"\x15collection_not_before\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13collectionNotBefore\x12N\n" +
	"\x15collection_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x13collectionExpiresAt\"\x92\x01\n" +
	"\x14ReportFlowLogRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fconsent_version\x18\x02 \x01(\x04R\x0econsentVersion\x128\n" +
	"\x06window\x18\x03 \x01(\v2 .endlessnet.client.v1.FlowWindowR\x06window\"\x89\x03\n" +
	"\n" +
	"FlowWindow\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12)\n" +
	"\x10destination_port\x18\x04 \x01(\rR\x0fdestinationPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1a\n" +
	"\bdecision\x18\x06 \x01(\tR\bdecision\x12\x17\n" +
	"\arule_id\x18\a \x01(\tR\x06ruleId\x12\x14\n" +
	"\x05bytes\x18\b \x01(\x04R\x05bytes\x12\x18\n" +
	"\apackets\x18\t \x01(\x04R\apackets\x12=\n" +
	"\fwindow_start\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\"4\n" +
	"\x15ReportFlowLogResponse\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId2\xc2\a\n" +
	"\vUserService\x12e\n" +
	"\fListAccounts\x12).endlessnet.client.v1.ListAccountsRequest\x1a*.endlessnet.client.v1.ListAccountsResponse\x12e\n" +
	"\fListNetworks\x12).endlessnet.client.v1.ListNetworksRequest\x1a*.endlessnet.client.v1.ListNetworksResponse\x12}\n" +
	"\x14ListAdvertisedRoutes\x121.endlessnet.client.v1.ListAdvertisedRoutesRequest\x1a2.endlessnet.client.v1.ListAdvertisedRoutesResponse\x12q\n" +
	"\x10ListBillingPlans\x12-.endlessnet.client.v1.ListBillingPlansRequest\x1a..endlessnet.client.v1.ListBillingPlansResponse\x12\x83\x01\n" +
	"\x16GetBillingSubscription\x123.endlessnet.client.v1.GetBillingSubscriptionRequest\x1a4.endlessnet.client.v1.GetBillingSubscriptionResponse\x12n\n" +
	"\x0fGetBillingUsage\x12,.endlessnet.client.v1.GetBillingUsageRequest\x1a-.endlessnet.client.v1.GetBillingUsageResponse\x12\x80\x01\n" +
	"\x15CreateBillingCheckout\x122.endlessnet.client.v1.CreateBillingCheckoutRequest\x1a3.endlessnet.client.v1.CreateBillingCheckoutResponse\x12z\n" +
	"\x13ListBillingInvoices\x120.endlessnet.client.v1.ListBillingInvoicesRequest\x1a1.endlessnet.client.v1.ListBillingInvoicesResponse2\xa4\x01\n" +
	"\x10ConnectorService\x12\x8f\x01\n" +
	"\x1aReportApplicationDiscovery\x127.endlessnet.client.v1.ReportApplicationDiscoveryRequest\x1a8.endlessnet.client.v1.ReportApplicationDiscoveryResponse2\xed\x01\n" +
	"\x0eFlowLogService\x12q\n" +
	"\x10GetFlowLogPolicy\x12-.endlessnet.client.v1.GetFlowLogPolicyRequest\x1a..endlessnet.client.v1.GetFlowLogPolicyResponse\x12h\n" +
	"\rReportFlowLog\x12*.endlessnet.client.v1.ReportFlowLogRequest\x1a+.endlessnet.client.v1.ReportFlowLogResponseBDZBgithub.com/endless-net/client-api/clientapi/v1/clientrpc;clientrpcb\x06proto3"

var (
	file_client_v1_client_proto_rawDescOnce sync.Once
	file_client_v1_client_proto_rawDescData []byte
)

func file_client_v1_client_proto_rawDescGZIP() []byte {
	file_client_v1_client_proto_rawDescOnce.Do(func() {
		file_client_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_client_proto_rawDesc), len(file_client_v1_client_proto_rawDesc)))
	})
	return file_client_v1_client_proto_rawDescData
}

var file_client_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_client_v1_client_proto_goTypes = []any{
	(*PageRequest)(nil),                        // 0: endlessnet.client.v1.PageRequest
	(*PageResponse)(nil),                       // 1: endlessnet.client.v1.PageResponse
	(*Account)(nil),                            // 2: endlessnet.client.v1.Account
	(*Network)(nil),                            // 3: endlessnet.client.v1.Network
	(*AdvertisedRoute)(nil),                    // 4: endlessnet.client.v1.AdvertisedRoute
	(*Plan)(nil),                               // 5: endlessnet.client.v1.Plan
	(*Subscription)(nil),                       // 6: endlessnet.client.v1.Subscription
	(*Usage)(nil),                              // 7: endlessnet.client.v1.Usage
	(*Checkout)(nil),                           // 8: endlessnet.client.v1.Checkout
	(*Invoice)(nil),                            // 9: endlessnet.client.v1.Invoice
	(*ListAccountsRequest)(nil),                // 10: endlessnet.client.v1.ListAccountsRequest
	(*ListAccountsResponse)(nil),               // 11: endlessnet.client.v1.ListAccountsResponse
	(*ListNetworksRequest)(nil),                // 12: endlessnet.client.v1.ListNetworksRequest
	(*ListNetworksResponse)(nil),               // 13: endlessnet.client.v1.ListNetworksResponse
	(*ListAdvertisedRoutesRequest)(nil),        // 14: endlessnet.client.v1.ListAdvertisedRoutesRequest
	(*ListAdvertisedRoutesResponse)(nil),       // 15: endlessnet.client.v1.ListAdvertisedRoutesResponse
	(*ListBillingPlansRequest)(nil),            // 16: endlessnet.client.v1.ListBillingPlansRequest
	(*ListBillingPlansResponse)(nil),           // 17: endlessnet.client.v1.ListBillingPlansResponse
	(*GetBillingSubscriptionRequest)(nil),      // 18: endlessnet.client.v1.GetBillingSubscriptionRequest
	(*GetBillingSubscriptionResponse)(nil),     // 19: endlessnet.client.v1.GetBillingSubscriptionResponse
	(*GetBillingUsageRequest)(nil),             // 20: endlessnet.client.v1.GetBillingUsageRequest
	(*GetBillingUsageResponse)(nil),            // 21: endlessnet.client.v1.GetBillingUsageResponse
	(*OperationMetadata)(nil),                  // 22: endlessnet.client.v1.OperationMetadata
	(*CreateBillingCheckoutRequest)(nil),       // 23: endlessnet.client.v1.CreateBillingCheckoutRequest
	(*CreateBillingCheckoutResponse)(nil),      // 24: endlessnet.client.v1.CreateBillingCheckoutResponse
	(*ListBillingInvoicesRequest)(nil),         // 25: endlessnet.client.v1.ListBillingInvoicesRequest
	(*ListBillingInvoicesResponse)(nil),        // 26: endlessnet.client.v1.ListBillingInvoicesResponse
	(*ReportApplicationDiscoveryRequest)(nil),  // 27: endlessnet.client.v1.ReportApplicationDiscoveryRequest
	(*ReportApplicationDiscoveryResponse)(nil), // 28: endlessnet.client.v1.ReportApplicationDiscoveryResponse
	(*GetFlowLogPolicyRequest)(nil),            // 29: endlessnet.client.v1.GetFlowLogPolicyRequest
	(*GetFlowLogPolicyResponse)(nil),           // 30: endlessnet.client.v1.GetFlowLogPolicyResponse
	(*ReportFlowLogRequest)(nil),               // 31: endlessnet.client.v1.ReportFlowLogRequest
	(*FlowWindow)(nil),                         // 32: endlessnet.client.v1.FlowWindow
	(*ReportFlowLogResponse)(nil),              // 33: endlessnet.client.v1.ReportFlowLogResponse
	(*timestamppb.Timestamp)(nil),              // 34: google.protobuf.Timestamp
}
var file_client_v1_client_proto_depIdxs = []int32{
	0,  // 0: endlessnet.client.v1.ListAccountsRequest.page:type_name -> endlessnet.client.v1.PageRequest
	2,  // 1: endlessnet.client.v1.ListAccountsResponse.accounts:type_name -> endlessnet.client.v1.Account
	1,  // 2: endlessnet.client.v1.ListAccountsResponse.page:type_name -> endlessnet.client.v1.PageResponse
	0,  // 3: endlessnet.client.v1.ListNetworksRequest.page:type_name -> endlessnet.client.v1.PageRequest
	3,  // 4: endlessnet.client.v1.ListNetworksResponse.networks:type_name -> endlessnet.client.v1.Network
	1,  // 5: endlessnet.client.v1.ListNetworksResponse.page:type_name -> endlessnet.client.v1.PageResponse
	0,  // 6: endlessnet.client.v1.ListAdvertisedRoutesRequest.page:type_name -> endlessnet.client.v1.PageRequest
	4,  // 7: endlessnet.client.v1.ListAdvertisedRoutesResponse.routes:type_name -> endlessnet.client.v1.AdvertisedRoute
	1,  // 8: endlessnet.client.v1.ListAdvertisedRoutesResponse.page:type_name -> endlessnet.client.v1.PageResponse
	5,  // 9: endlessnet.client.v1.ListBillingPlansResponse.plans:type_name -> endlessnet.client.v1.Plan
	6,  // 10: endlessnet.client.v1.GetBillingSubscriptionResponse.subscription:type_name -> endlessnet.client.v1.Subscription
	7,  // 11: endlessnet.client.v1.GetBillingUsageResponse.usage:type_name -> endlessnet.client.v1.Usage
	22, // 12: endlessnet.client.v1.CreateBillingCheckoutRequest.operation:type_name -> endlessnet.client.v1.OperationMetadata
	8,  // 13: endlessnet.client.v1.CreateBillingCheckoutResponse.checkout:type_name -> endlessnet.client.v1.Checkout
	0,  // 14: endlessnet.client.v1.ListBillingInvoicesRequest.page:type_name -> endlessnet.client.v1.PageRequest
	9,  // 15: endlessnet.client.v1.ListBillingInvoicesResponse.invoices:type_name -> endlessnet.client.v1.Invoice
	1,  // 16: endlessnet.client.v1.ListBillingInvoicesResponse.page:type_name -> endlessnet.client.v1.PageResponse
	34, // 17: endlessnet.client.v1.GetFlowLogPolicyResponse.collection_not_before:type_name -> google.protobuf.Timestamp
	34, // 18: endlessnet.client.v1.GetFlowLogPolicyResponse.collection_expires_at:type_name -> google.protobuf.Timestamp
	32, // 19: endlessnet.client.v1.ReportFlowLogRequest.window:type_name -> endlessnet.client.v1.FlowWindow
	34, // 20: endlessnet.client.v1.FlowWindow.window_start:type_name -> google.protobuf.Timestamp
	34, // 21: endlessnet.client.v1.FlowWindow.window_end:type_name -> google.protobuf.Timestamp
	10, // 22: endlessnet.client.v1.UserService.ListAccounts:input_type -> endlessnet.client.v1.ListAccountsRequest
	12, // 23: endlessnet.client.v1.UserService.ListNetworks:input_type -> endlessnet.client.v1.ListNetworksRequest
	14, // 24: endlessnet.client.v1.UserService.ListAdvertisedRoutes:input_type -> endlessnet.client.v1.ListAdvertisedRoutesRequest
	16, // 25: endlessnet.client.v1.UserService.ListBillingPlans:input_type -> endlessnet.client.v1.ListBillingPlansRequest
	18, // 26: endlessnet.client.v1.UserService.GetBillingSubscription:input_type -> endlessnet.client.v1.GetBillingSubscriptionRequest
	20, // 27: endlessnet.client.v1.UserService.GetBillingUsage:input_type -> endlessnet.client.v1.GetBillingUsageRequest
	23, // 28: endlessnet.client.v1.UserService.CreateBillingCheckout:input_type -> endlessnet.client.v1.CreateBillingCheckoutRequest
	25, // 29: endlessnet.client.v1.UserService.ListBillingInvoices:input_type -> endlessnet.client.v1.ListBillingInvoicesRequest
	27, // 30: endlessnet.client.v1.ConnectorService.ReportApplicationDiscovery:input_type -> endlessnet.client.v1.ReportApplicationDiscoveryRequest
	29, // 31: endlessnet.client.v1.FlowLogService.GetFlowLogPolicy:input_type -> endlessnet.client.v1.GetFlowLogPolicyRequest
	31, // 32: endlessnet.client.v1.FlowLogService.ReportFlowLog:input_type -> endlessnet.client.v1.ReportFlowLogRequest
	11, // 33: endlessnet.client.v1.UserService.ListAccounts:output_type -> endlessnet.client.v1.ListAccountsResponse
	13, // 34: endlessnet.client.v1.UserService.ListNetworks:output_type -> endlessnet.client.v1.ListNetworksResponse
	15, // 35: endlessnet.client.v1.UserService.ListAdvertisedRoutes:output_type -> endlessnet.client.v1.ListAdvertisedRoutesResponse
	17, // 36: endlessnet.client.v1.UserService.ListBillingPlans:output_type -> endlessnet.client.v1.ListBillingPlansResponse
	19, // 37: endlessnet.client.v1.UserService.GetBillingSubscription:output_type -> endlessnet.client.v1.GetBillingSubscriptionResponse
	21, // 38: endlessnet.client.v1.UserService.GetBillingUsage:output_type -> endlessnet.client.v1.GetBillingUsageResponse
	24, // 39: endlessnet.client.v1.UserService.CreateBillingCheckout:output_type -> endlessnet.client.v1.CreateBillingCheckoutResponse
	26, // 40: endlessnet.client.v1.UserService.ListBillingInvoices:output_type -> endlessnet.client.v1.ListBillingInvoicesResponse
	28, // 41: endlessnet.client.v1.ConnectorService.ReportApplicationDiscovery:output_type -> endlessnet.client.v1.ReportApplicationDiscoveryResponse
	30, // 42: endlessnet.client.v1.FlowLogService.GetFlowLogPolicy:output_type -> endlessnet.client.v1.GetFlowLogPolicyResponse
	33, // 43: endlessnet.client.v1.FlowLogService.ReportFlowLog:output_type -> endlessnet.client.v1.ReportFlowLogResponse
	33, // [33:44] is the sub-list for method output_type
	22, // [22:33] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_client_v1_client_proto_init() }
func file_client_v1_client_proto_init() {
	if File_client_v1_client_proto != nil {
		return
	}
	file_client_v1_client_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_client_proto_rawDesc), len(file_client_v1_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_client_v1_client_proto_goTypes,
		DependencyIndexes: file_client_v1_client_proto_depIdxs,
		MessageInfos:      file_client_v1_client_proto_msgTypes,
	}.Build()
	File_client_v1_client_proto = out.File
	file_client_v1_client_proto_goTypes = nil
	file_client_v1_client_proto_depIdxs = nil
}
