// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: client/v1/client.proto

package clientrpcconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	clientrpc "github.com/endless-net/client-api/clientapi/v1/clientrpc"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "endlessnet.client.v1.UserService"
	// ConnectorServiceName is the fully-qualified name of the ConnectorService service.
	ConnectorServiceName = "endlessnet.client.v1.ConnectorService"
	// FlowLogServiceName is the fully-qualified name of the FlowLogService service.
	FlowLogServiceName = "endlessnet.client.v1.FlowLogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceListAccountsProcedure is the fully-qualified name of the UserService's ListAccounts
	// RPC.
	UserServiceListAccountsProcedure = "/endlessnet.client.v1.UserService/ListAccounts"
	// UserServiceListNetworksProcedure is the fully-qualified name of the UserService's ListNetworks
	// RPC.
	UserServiceListNetworksProcedure = "/endlessnet.client.v1.UserService/ListNetworks"
	// UserServiceListAdvertisedRoutesProcedure is the fully-qualified name of the UserService's
	// ListAdvertisedRoutes RPC.
	UserServiceListAdvertisedRoutesProcedure = "/endlessnet.client.v1.UserService/ListAdvertisedRoutes"
	// UserServiceListBillingPlansProcedure is the fully-qualified name of the UserService's
	// ListBillingPlans RPC.
	UserServiceListBillingPlansProcedure = "/endlessnet.client.v1.UserService/ListBillingPlans"
	// UserServiceGetBillingSubscriptionProcedure is the fully-qualified name of the UserService's
	// GetBillingSubscription RPC.
	UserServiceGetBillingSubscriptionProcedure = "/endlessnet.client.v1.UserService/GetBillingSubscription"
	// UserServiceGetBillingUsageProcedure is the fully-qualified name of the UserService's
	// GetBillingUsage RPC.
	UserServiceGetBillingUsageProcedure = "/endlessnet.client.v1.UserService/GetBillingUsage"
	// UserServiceCreateBillingCheckoutProcedure is the fully-qualified name of the UserService's
	// CreateBillingCheckout RPC.
	UserServiceCreateBillingCheckoutProcedure = "/endlessnet.client.v1.UserService/CreateBillingCheckout"
	// UserServiceListBillingInvoicesProcedure is the fully-qualified name of the UserService's
	// ListBillingInvoices RPC.
	UserServiceListBillingInvoicesProcedure = "/endlessnet.client.v1.UserService/ListBillingInvoices"
	// ConnectorServiceReportApplicationDiscoveryProcedure is the fully-qualified name of the
	// ConnectorService's ReportApplicationDiscovery RPC.
	ConnectorServiceReportApplicationDiscoveryProcedure = "/endlessnet.client.v1.ConnectorService/ReportApplicationDiscovery"
	// FlowLogServiceGetFlowLogPolicyProcedure is the fully-qualified name of the FlowLogService's
	// GetFlowLogPolicy RPC.
	FlowLogServiceGetFlowLogPolicyProcedure = "/endlessnet.client.v1.FlowLogService/GetFlowLogPolicy"
	// FlowLogServiceReportFlowLogProcedure is the fully-qualified name of the FlowLogService's
	// ReportFlowLog RPC.
	FlowLogServiceReportFlowLogProcedure = "/endlessnet.client.v1.FlowLogService/ReportFlowLog"
)

// UserServiceClient is a client for the endlessnet.client.v1.UserService service.
type UserServiceClient interface {
	ListAccounts(context.Context, *connect.Request[clientrpc.ListAccountsRequest]) (*connect.Response[clientrpc.ListAccountsResponse], error)
	ListNetworks(context.Context, *connect.Request[clientrpc.ListNetworksRequest]) (*connect.Response[clientrpc.ListNetworksResponse], error)
	ListAdvertisedRoutes(context.Context, *connect.Request[clientrpc.ListAdvertisedRoutesRequest]) (*connect.Response[clientrpc.ListAdvertisedRoutesResponse], error)
	ListBillingPlans(context.Context, *connect.Request[clientrpc.ListBillingPlansRequest]) (*connect.Response[clientrpc.ListBillingPlansResponse], error)
	GetBillingSubscription(context.Context, *connect.Request[clientrpc.GetBillingSubscriptionRequest]) (*connect.Response[clientrpc.GetBillingSubscriptionResponse], error)
	GetBillingUsage(context.Context, *connect.Request[clientrpc.GetBillingUsageRequest]) (*connect.Response[clientrpc.GetBillingUsageResponse], error)
	CreateBillingCheckout(context.Context, *connect.Request[clientrpc.CreateBillingCheckoutRequest]) (*connect.Response[clientrpc.CreateBillingCheckoutResponse], error)
	ListBillingInvoices(context.Context, *connect.Request[clientrpc.ListBillingInvoicesRequest]) (*connect.Response[clientrpc.ListBillingInvoicesResponse], error)
}

// NewUserServiceClient constructs a client for the endlessnet.client.v1.UserService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := clientrpc.File_client_v1_client_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		listAccounts: connect.NewClient[clientrpc.ListAccountsRequest, clientrpc.ListAccountsResponse](
			httpClient,
			baseURL+UserServiceListAccountsProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListAccounts")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[clientrpc.ListNetworksRequest, clientrpc.ListNetworksResponse](
			httpClient,
			baseURL+UserServiceListNetworksProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		listAdvertisedRoutes: connect.NewClient[clientrpc.ListAdvertisedRoutesRequest, clientrpc.ListAdvertisedRoutesResponse](
			httpClient,
			baseURL+UserServiceListAdvertisedRoutesProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListAdvertisedRoutes")),
			connect.WithClientOptions(opts...),
		),
		listBillingPlans: connect.NewClient[clientrpc.ListBillingPlansRequest, clientrpc.ListBillingPlansResponse](
			httpClient,
			baseURL+UserServiceListBillingPlansProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListBillingPlans")),
			connect.WithClientOptions(opts...),
		),
		getBillingSubscription: connect.NewClient[clientrpc.GetBillingSubscriptionRequest, clientrpc.GetBillingSubscriptionResponse](
			httpClient,
			baseURL+UserServiceGetBillingSubscriptionProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetBillingSubscription")),
			connect.WithClientOptions(opts...),
		),
		getBillingUsage: connect.NewClient[clientrpc.GetBillingUsageRequest, clientrpc.GetBillingUsageResponse](
			httpClient,
			baseURL+UserServiceGetBillingUsageProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetBillingUsage")),
			connect.WithClientOptions(opts...),
		),
		createBillingCheckout: connect.NewClient[clientrpc.CreateBillingCheckoutRequest, clientrpc.CreateBillingCheckoutResponse](
			httpClient,
			baseURL+UserServiceCreateBillingCheckoutProcedure,
			connect.WithSchema(userServiceMethods.ByName("CreateBillingCheckout")),
			connect.WithClientOptions(opts...),
		),
		listBillingInvoices: connect.NewClient[clientrpc.ListBillingInvoicesRequest, clientrpc.ListBillingInvoicesResponse](
			httpClient,
			baseURL+UserServiceListBillingInvoicesProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListBillingInvoices")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	listAccounts           *connect.Client[clientrpc.ListAccountsRequest, clientrpc.ListAccountsResponse]
	listNetworks           *connect.Client[clientrpc.ListNetworksRequest, clientrpc.ListNetworksResponse]
	listAdvertisedRoutes   *connect.Client[clientrpc.ListAdvertisedRoutesRequest, clientrpc.ListAdvertisedRoutesResponse]
	listBillingPlans       *connect.Client[clientrpc.ListBillingPlansRequest, clientrpc.ListBillingPlansResponse]
	getBillingSubscription *connect.Client[clientrpc.GetBillingSubscriptionRequest, clientrpc.GetBillingSubscriptionResponse]
	getBillingUsage        *connect.Client[clientrpc.GetBillingUsageRequest, clientrpc.GetBillingUsageResponse]
	createBillingCheckout  *connect.Client[clientrpc.CreateBillingCheckoutRequest, clientrpc.CreateBillingCheckoutResponse]
	listBillingInvoices    *connect.Client[clientrpc.ListBillingInvoicesRequest, clientrpc.ListBillingInvoicesResponse]
}

// ListAccounts calls endlessnet.client.v1.UserService.ListAccounts.
func (c *userServiceClient) ListAccounts(ctx context.Context, req *connect.Request[clientrpc.ListAccountsRequest]) (*connect.Response[clientrpc.ListAccountsResponse], error) {
	return c.listAccounts.CallUnary(ctx, req)
}

// ListNetworks calls endlessnet.client.v1.UserService.ListNetworks.
func (c *userServiceClient) ListNetworks(ctx context.Context, req *connect.Request[clientrpc.ListNetworksRequest]) (*connect.Response[clientrpc.ListNetworksResponse], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// ListAdvertisedRoutes calls endlessnet.client.v1.UserService.ListAdvertisedRoutes.
func (c *userServiceClient) ListAdvertisedRoutes(ctx context.Context, req *connect.Request[clientrpc.ListAdvertisedRoutesRequest]) (*connect.Response[clientrpc.ListAdvertisedRoutesResponse], error) {
	return c.listAdvertisedRoutes.CallUnary(ctx, req)
}

// ListBillingPlans calls endlessnet.client.v1.UserService.ListBillingPlans.
func (c *userServiceClient) ListBillingPlans(ctx context.Context, req *connect.Request[clientrpc.ListBillingPlansRequest]) (*connect.Response[clientrpc.ListBillingPlansResponse], error) {
	return c.listBillingPlans.CallUnary(ctx, req)
}

// GetBillingSubscription calls endlessnet.client.v1.UserService.GetBillingSubscription.
func (c *userServiceClient) GetBillingSubscription(ctx context.Context, req *connect.Request[clientrpc.GetBillingSubscriptionRequest]) (*connect.Response[clientrpc.GetBillingSubscriptionResponse], error) {
	return c.getBillingSubscription.CallUnary(ctx, req)
}

// GetBillingUsage calls endlessnet.client.v1.UserService.GetBillingUsage.
func (c *userServiceClient) GetBillingUsage(ctx context.Context, req *connect.Request[clientrpc.GetBillingUsageRequest]) (*connect.Response[clientrpc.GetBillingUsageResponse], error) {
	return c.getBillingUsage.CallUnary(ctx, req)
}

// CreateBillingCheckout calls endlessnet.client.v1.UserService.CreateBillingCheckout.
func (c *userServiceClient) CreateBillingCheckout(ctx context.Context, req *connect.Request[clientrpc.CreateBillingCheckoutRequest]) (*connect.Response[clientrpc.CreateBillingCheckoutResponse], error) {
	return c.createBillingCheckout.CallUnary(ctx, req)
}

// ListBillingInvoices calls endlessnet.client.v1.UserService.ListBillingInvoices.
func (c *userServiceClient) ListBillingInvoices(ctx context.Context, req *connect.Request[clientrpc.ListBillingInvoicesRequest]) (*connect.Response[clientrpc.ListBillingInvoicesResponse], error) {
	return c.listBillingInvoices.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the endlessnet.client.v1.UserService service.
type UserServiceHandler interface {
	ListAccounts(context.Context, *connect.Request[clientrpc.ListAccountsRequest]) (*connect.Response[clientrpc.ListAccountsResponse], error)
	ListNetworks(context.Context, *connect.Request[clientrpc.ListNetworksRequest]) (*connect.Response[clientrpc.ListNetworksResponse], error)
	ListAdvertisedRoutes(context.Context, *connect.Request[clientrpc.ListAdvertisedRoutesRequest]) (*connect.Response[clientrpc.ListAdvertisedRoutesResponse], error)
	ListBillingPlans(context.Context, *connect.Request[clientrpc.ListBillingPlansRequest]) (*connect.Response[clientrpc.ListBillingPlansResponse], error)
	GetBillingSubscription(context.Context, *connect.Request[clientrpc.GetBillingSubscriptionRequest]) (*connect.Response[clientrpc.GetBillingSubscriptionResponse], error)
	GetBillingUsage(context.Context, *connect.Request[clientrpc.GetBillingUsageRequest]) (*connect.Response[clientrpc.GetBillingUsageResponse], error)
	CreateBillingCheckout(context.Context, *connect.Request[clientrpc.CreateBillingCheckoutRequest]) (*connect.Response[clientrpc.CreateBillingCheckoutResponse], error)
	ListBillingInvoices(context.Context, *connect.Request[clientrpc.ListBillingInvoicesRequest]) (*connect.Response[clientrpc.ListBillingInvoicesResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := clientrpc.File_client_v1_client_proto.Services().ByName("UserService").Methods()
	userServiceListAccountsHandler := connect.NewUnaryHandler(
		UserServiceListAccountsProcedure,
		svc.ListAccounts,
		connect.WithSchema(userServiceMethods.ByName("ListAccounts")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListNetworksHandler := connect.NewUnaryHandler(
		UserServiceListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(userServiceMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListAdvertisedRoutesHandler := connect.NewUnaryHandler(
		UserServiceListAdvertisedRoutesProcedure,
		svc.ListAdvertisedRoutes,
		connect.WithSchema(userServiceMethods.ByName("ListAdvertisedRoutes")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListBillingPlansHandler := connect.NewUnaryHandler(
		UserServiceListBillingPlansProcedure,
		svc.ListBillingPlans,
		connect.WithSchema(userServiceMethods.ByName("ListBillingPlans")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetBillingSubscriptionHandler := connect.NewUnaryHandler(
		UserServiceGetBillingSubscriptionProcedure,
		svc.GetBillingSubscription,
		connect.WithSchema(userServiceMethods.ByName("GetBillingSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetBillingUsageHandler := connect.NewUnaryHandler(
		UserServiceGetBillingUsageProcedure,
		svc.GetBillingUsage,
		connect.WithSchema(userServiceMethods.ByName("GetBillingUsage")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceCreateBillingCheckoutHandler := connect.NewUnaryHandler(
		UserServiceCreateBillingCheckoutProcedure,
		svc.CreateBillingCheckout,
		connect.WithSchema(userServiceMethods.ByName("CreateBillingCheckout")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListBillingInvoicesHandler := connect.NewUnaryHandler(
		UserServiceListBillingInvoicesProcedure,
		svc.ListBillingInvoices,
		connect.WithSchema(userServiceMethods.ByName("ListBillingInvoices")),
		connect.WithHandlerOptions(opts...),
	)
	return "/endlessnet.client.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceListAccountsProcedure:
			userServiceListAccountsHandler.ServeHTTP(w, r)
		case UserServiceListNetworksProcedure:
			userServiceListNetworksHandler.ServeHTTP(w, r)
		case UserServiceListAdvertisedRoutesProcedure:
			userServiceListAdvertisedRoutesHandler.ServeHTTP(w, r)
		case UserServiceListBillingPlansProcedure:
			userServiceListBillingPlansHandler.ServeHTTP(w, r)
		case UserServiceGetBillingSubscriptionProcedure:
			userServiceGetBillingSubscriptionHandler.ServeHTTP(w, r)
		case UserServiceGetBillingUsageProcedure:
			userServiceGetBillingUsageHandler.ServeHTTP(w, r)
		case UserServiceCreateBillingCheckoutProcedure:
			userServiceCreateBillingCheckoutHandler.ServeHTTP(w, r)
		case UserServiceListBillingInvoicesProcedure:
			userServiceListBillingInvoicesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) ListAccounts(context.Context, *connect.Request[clientrpc.ListAccountsRequest]) (*connect.Response[clientrpc.ListAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.ListAccounts is not implemented"))
}

func (UnimplementedUserServiceHandler) ListNetworks(context.Context, *connect.Request[clientrpc.ListNetworksRequest]) (*connect.Response[clientrpc.ListNetworksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.ListNetworks is not implemented"))
}

func (UnimplementedUserServiceHandler) ListAdvertisedRoutes(context.Context, *connect.Request[clientrpc.ListAdvertisedRoutesRequest]) (*connect.Response[clientrpc.ListAdvertisedRoutesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.ListAdvertisedRoutes is not implemented"))
}

func (UnimplementedUserServiceHandler) ListBillingPlans(context.Context, *connect.Request[clientrpc.ListBillingPlansRequest]) (*connect.Response[clientrpc.ListBillingPlansResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.ListBillingPlans is not implemented"))
}

func (UnimplementedUserServiceHandler) GetBillingSubscription(context.Context, *connect.Request[clientrpc.GetBillingSubscriptionRequest]) (*connect.Response[clientrpc.GetBillingSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.GetBillingSubscription is not implemented"))
}

func (UnimplementedUserServiceHandler) GetBillingUsage(context.Context, *connect.Request[clientrpc.GetBillingUsageRequest]) (*connect.Response[clientrpc.GetBillingUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.GetBillingUsage is not implemented"))
}

func (UnimplementedUserServiceHandler) CreateBillingCheckout(context.Context, *connect.Request[clientrpc.CreateBillingCheckoutRequest]) (*connect.Response[clientrpc.CreateBillingCheckoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.CreateBillingCheckout is not implemented"))
}

func (UnimplementedUserServiceHandler) ListBillingInvoices(context.Context, *connect.Request[clientrpc.ListBillingInvoicesRequest]) (*connect.Response[clientrpc.ListBillingInvoicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.UserService.ListBillingInvoices is not implemented"))
}

// ConnectorServiceClient is a client for the endlessnet.client.v1.ConnectorService service.
type ConnectorServiceClient interface {
	ReportApplicationDiscovery(context.Context, *connect.Request[clientrpc.ReportApplicationDiscoveryRequest]) (*connect.Response[clientrpc.ReportApplicationDiscoveryResponse], error)
}

// NewConnectorServiceClient constructs a client for the endlessnet.client.v1.ConnectorService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectorServiceMethods := clientrpc.File_client_v1_client_proto.Services().ByName("ConnectorService").Methods()
	return &connectorServiceClient{
		reportApplicationDiscovery: connect.NewClient[clientrpc.ReportApplicationDiscoveryRequest, clientrpc.ReportApplicationDiscoveryResponse](
			httpClient,
			baseURL+ConnectorServiceReportApplicationDiscoveryProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("ReportApplicationDiscovery")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectorServiceClient implements ConnectorServiceClient.
type connectorServiceClient struct {
	reportApplicationDiscovery *connect.Client[clientrpc.ReportApplicationDiscoveryRequest, clientrpc.ReportApplicationDiscoveryResponse]
}

// ReportApplicationDiscovery calls
// endlessnet.client.v1.ConnectorService.ReportApplicationDiscovery.
func (c *connectorServiceClient) ReportApplicationDiscovery(ctx context.Context, req *connect.Request[clientrpc.ReportApplicationDiscoveryRequest]) (*connect.Response[clientrpc.ReportApplicationDiscoveryResponse], error) {
	return c.reportApplicationDiscovery.CallUnary(ctx, req)
}

// ConnectorServiceHandler is an implementation of the endlessnet.client.v1.ConnectorService
// service.
type ConnectorServiceHandler interface {
	ReportApplicationDiscovery(context.Context, *connect.Request[clientrpc.ReportApplicationDiscoveryRequest]) (*connect.Response[clientrpc.ReportApplicationDiscoveryResponse], error)
}

// NewConnectorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectorServiceHandler(svc ConnectorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectorServiceMethods := clientrpc.File_client_v1_client_proto.Services().ByName("ConnectorService").Methods()
	connectorServiceReportApplicationDiscoveryHandler := connect.NewUnaryHandler(
		ConnectorServiceReportApplicationDiscoveryProcedure,
		svc.ReportApplicationDiscovery,
		connect.WithSchema(connectorServiceMethods.ByName("ReportApplicationDiscovery")),
		connect.WithHandlerOptions(opts...),
	)
	return "/endlessnet.client.v1.ConnectorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectorServiceReportApplicationDiscoveryProcedure:
			connectorServiceReportApplicationDiscoveryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectorServiceHandler struct{}

func (UnimplementedConnectorServiceHandler) ReportApplicationDiscovery(context.Context, *connect.Request[clientrpc.ReportApplicationDiscoveryRequest]) (*connect.Response[clientrpc.ReportApplicationDiscoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.ConnectorService.ReportApplicationDiscovery is not implemented"))
}

// FlowLogServiceClient is a client for the endlessnet.client.v1.FlowLogService service.
type FlowLogServiceClient interface {
	GetFlowLogPolicy(context.Context, *connect.Request[clientrpc.GetFlowLogPolicyRequest]) (*connect.Response[clientrpc.GetFlowLogPolicyResponse], error)
	ReportFlowLog(context.Context, *connect.Request[clientrpc.ReportFlowLogRequest]) (*connect.Response[clientrpc.ReportFlowLogResponse], error)
}

// NewFlowLogServiceClient constructs a client for the endlessnet.client.v1.FlowLogService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFlowLogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FlowLogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	flowLogServiceMethods := clientrpc.File_client_v1_client_proto.Services().ByName("FlowLogService").Methods()
	return &flowLogServiceClient{
		getFlowLogPolicy: connect.NewClient[clientrpc.GetFlowLogPolicyRequest, clientrpc.GetFlowLogPolicyResponse](
			httpClient,
			baseURL+FlowLogServiceGetFlowLogPolicyProcedure,
			connect.WithSchema(flowLogServiceMethods.ByName("GetFlowLogPolicy")),
			connect.WithClientOptions(opts...),
		),
		reportFlowLog: connect.NewClient[clientrpc.ReportFlowLogRequest, clientrpc.ReportFlowLogResponse](
			httpClient,
			baseURL+FlowLogServiceReportFlowLogProcedure,
			connect.WithSchema(flowLogServiceMethods.ByName("ReportFlowLog")),
			connect.WithClientOptions(opts...),
		),
	}
}

// flowLogServiceClient implements FlowLogServiceClient.
type flowLogServiceClient struct {
	getFlowLogPolicy *connect.Client[clientrpc.GetFlowLogPolicyRequest, clientrpc.GetFlowLogPolicyResponse]
	reportFlowLog    *connect.Client[clientrpc.ReportFlowLogRequest, clientrpc.ReportFlowLogResponse]
}

// GetFlowLogPolicy calls endlessnet.client.v1.FlowLogService.GetFlowLogPolicy.
func (c *flowLogServiceClient) GetFlowLogPolicy(ctx context.Context, req *connect.Request[clientrpc.GetFlowLogPolicyRequest]) (*connect.Response[clientrpc.GetFlowLogPolicyResponse], error) {
	return c.getFlowLogPolicy.CallUnary(ctx, req)
}

// ReportFlowLog calls endlessnet.client.v1.FlowLogService.ReportFlowLog.
func (c *flowLogServiceClient) ReportFlowLog(ctx context.Context, req *connect.Request[clientrpc.ReportFlowLogRequest]) (*connect.Response[clientrpc.ReportFlowLogResponse], error) {
	return c.reportFlowLog.CallUnary(ctx, req)
}

// FlowLogServiceHandler is an implementation of the endlessnet.client.v1.FlowLogService service.
type FlowLogServiceHandler interface {
	GetFlowLogPolicy(context.Context, *connect.Request[clientrpc.GetFlowLogPolicyRequest]) (*connect.Response[clientrpc.GetFlowLogPolicyResponse], error)
	ReportFlowLog(context.Context, *connect.Request[clientrpc.ReportFlowLogRequest]) (*connect.Response[clientrpc.ReportFlowLogResponse], error)
}

// NewFlowLogServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFlowLogServiceHandler(svc FlowLogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	flowLogServiceMethods := clientrpc.File_client_v1_client_proto.Services().ByName("FlowLogService").Methods()
	flowLogServiceGetFlowLogPolicyHandler := connect.NewUnaryHandler(
		FlowLogServiceGetFlowLogPolicyProcedure,
		svc.GetFlowLogPolicy,
		connect.WithSchema(flowLogServiceMethods.ByName("GetFlowLogPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	flowLogServiceReportFlowLogHandler := connect.NewUnaryHandler(
		FlowLogServiceReportFlowLogProcedure,
		svc.ReportFlowLog,
		connect.WithSchema(flowLogServiceMethods.ByName("ReportFlowLog")),
		connect.WithHandlerOptions(opts...),
	)
	return "/endlessnet.client.v1.FlowLogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FlowLogServiceGetFlowLogPolicyProcedure:
			flowLogServiceGetFlowLogPolicyHandler.ServeHTTP(w, r)
		case FlowLogServiceReportFlowLogProcedure:
			flowLogServiceReportFlowLogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFlowLogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFlowLogServiceHandler struct{}

func (UnimplementedFlowLogServiceHandler) GetFlowLogPolicy(context.Context, *connect.Request[clientrpc.GetFlowLogPolicyRequest]) (*connect.Response[clientrpc.GetFlowLogPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.FlowLogService.GetFlowLogPolicy is not implemented"))
}

func (UnimplementedFlowLogServiceHandler) ReportFlowLog(context.Context, *connect.Request[clientrpc.ReportFlowLogRequest]) (*connect.Response[clientrpc.ReportFlowLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("endlessnet.client.v1.FlowLogService.ReportFlowLog is not implemented"))
}
